### ISSUE TITLE
License GPL-3.0-only or GPL-3.0-or-later?

### ISSUE THREAD

**Issue by zen0bit** [termkit/gama#15]
I am adding your nice program to Void Linux.
[PR](https://github.com/void-linux/void-packages/pull/48123)
And this question raised.

Can license be please clarified?

Thanks for answer, and gama itself

👍 Keep up

**Comment by canack** [comment]
Hi @zen0bit, I've updated the description. : https://github.com/termkit/gama/commit/75465c68c8804089b4a16bddb062e83976a6de4e

Thank you for interest! 🚀
