### ISSUE TITLE
Add Feature: Sort

### ISSUE THREAD

**Issue by canack** [termkit/gama#2]
- [ ] Sort repositories
- [ ] Sort workflows

**Comment by fleimkeipa** [comment]
We have sort query on api for Repositories. We can add repositories sort on api.
Workflows doesn't have sort on api. We can sort workflows with golang sort packages

**Comment by canack** [comment]
Hmm, actually I though post sort stage. We can define a keymap for sort, like `s` button.
We can define different sort actions each time we press `s` button. Like `sort by name`  `sort by workflow count`  etc.

**Comment by canack** [comment]
Additional note: We can do this operation usecase layer. Usecase can accept `sortBy` as string. Handler side keeps only sorting method in their struct.
