### ISSUE TITLE
Feature: Pagination for the repositories

### ISSUE THREAD

**Issue by semihbkgr** [termkit/gama#24]
In the `ListRepositories` request, the query param  of `per_page` can be `100` at max. 

from the doc:

> `per_page` integer
The number of results per page (max 100).

so I think, would better to have pagination in the repositories tab (loading pages lazily).

**Comment by canack** [comment]
Hi, thank you for your interest 🍀 
You right, we'll break the limits in few days 🚀

But I think to implement "favorite repositories" feature. May lazy load can break this functionality.  
See : https://github.com/termkit/gama/issues/1

**Comment by canack** [comment]
I've updated repositories limit 500 for now.
I didn't find proper way to fetch all repositories with fastest way.
As far as I see, GitHub doesn't provide count of repositories, thus I can't run static sized go routines. So, each request should be wait next request's response to do an action.
