### ISSUE TITLE
Add binary releases for platform "linux/arm64" (ABI: "aarch64")

### ISSUE THREAD

**Issue by nifr** [termkit/gama#28]
First of all: THANKS for this great open-source project ❤️ 

I took it for a spin today and was really impressed 😮 

Could you please add binary releases for platform `linux/arm64`?

These binaries are required for use with:
* Docker Images on Apple M1/M2/M3 hardware
* IOT Devices like Raspberry Pi Zero 2 / Pi 3 / Pi 4 / Pi 5
* Cloud VMs (Ampere) like AWS Graviton / Hetzner CAX-Series

**Comment by canack** [comment]
Thank you for interested in gama! 🚀 I'll add in few days!

**Comment by canack** [comment]
@nifr I've merged the requirements. I'll publish a release at next Monday. 🚀
