### ISSUE TITLE
Resize the 'Trigger' - 'Key' column

### ISSUE THREAD

**Issue by gormelof** [termkit/gama#35]
In the trigger section, I couldn't see long-named keys. Maybe we can resize that column 🤔
Or, When we hover over it, we can show it below.

<img width="1056" alt="example-image" src="https://github.com/termkit/gama/assets/6938857/239f42e1-587e-4108-9e29-0c35acd7e615">

**Comment by canack** [comment]
Thank you for interest! I'll make dynamic resize feature like at repositories & workflow tab
