### ISSUE TITLE
`make build` fails with "toolchain not available" error

### ISSUE THREAD

**Issue by VeyronSakai** [termkit/gama#54]
## Overview
I got an error message "go: download go1.22 for darwin/arm64: toolchain not available" when running `make build`.

```sh
% make build
Getting latest Git tag...
v1.1.4
CGO_ENABLED=0 go build -ldflags="-s -w -X main.Version=v1.1.4" -o release/gama main.go
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
make: *** [build] Error 1
```

## Execution environment
OS: macOS Sonoma 14.4.1
Chip: Apple M2 Max

**Comment by canack** [comment]
Thank you for contribute! PR has been merged! ⭐
